[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "meantools"
authors = [{name = "Kumar", email = "kumar.singh@wur.nl"}]
dynamic = ["version", "description"]
